CREATE DATABASE WIKISALES;

CREATE TABLE DOCUMENT_TYPE(
    DCT_ID INT AUTO_INCREMENT,
    DCT_DESCRIPTION VARCHAR(20),
    CONSTRAINT PK_DOCUMENT_ID PRIMARY KEY  (DCT_ID)
);

CREATE TABLE CITY(
    CTY_ID INT AUTO_INCREMENT,
    CTY_NAME VARCHAR(200),
    CONSTRAINT PK_CITY_ID PRIMARY KEY  (CTY_ID)
);

CREATE TABLE PRODUCT_TYPE(
    PDT_ID INT AUTO_INCREMENT,
    PDT_DESCRIPTION VARCHAR(20),
    CONSTRAINT PK_PRODUCT_TYPE_ID PRIMARY KEY  (PDT_ID)
);

CREATE TABLE METHOD_PAYMENT(
    MTP_ID INT AUTO_INCREMENT,
    MTP_DESCRIPTION VARCHAR(20),
    CONSTRAINT PK_METHOD_PAYMENT_ID PRIMARY KEY  (MTP_ID)
);

CREATE TABLE DOCUMENT(
    DOC_ID INT AUTO_INCREMENT,
    DOC_NUMBER VARCHAR(20),
    DOC_DCTID INT,
    CONSTRAINT PK_CUSTOMER_DOC_ID PRIMARY KEY (DOC_ID),
    CONSTRAINT FK_DOCUMENT_TYPE FOREIGN KEY (DOC_DCTID) REFERENCES DOCUMENT_TYPE(DCT_ID)
);

CREATE TABLE SUPPLIER(
    SUP_ID INT AUTO_INCREMENT,
    SUP_NAME VARCHAR(20),
    SUP_LASTNAME VARCHAR(20),
    SUP_TRADENAME VARCHAR(50),
    SUP_ADDRESS VARCHAR(200),
    SUP_CTYID INT,
    SUP_DOCID INT,
    CONSTRAINT PK_SUPPLIER_ID PRIMARY KEY  (SUP_ID),
    CONSTRAINT FK_SUPCITY FOREIGN KEY  (SUP_CTYID) REFERENCES CITY(CTY_ID), 
    CONSTRAINT FK_SUPDOC FOREIGN KEY  (SUP_DOCID) REFERENCES DOCUMENT(DOC_ID)
);

CREATE TABLE CUSTOMER_TYPE(
    CUT_ID INT AUTO_INCREMENT,
    CUT_DESCRIPTION VARCHAR(20),
    CONSTRAINT PK_CUSTOMER_TYPE_ID PRIMARY KEY  (CUT_ID)
);

CREATE TABLE CUSTOMER(
    CUS_ID INT AUTO_INCREMENT,
    CUS_DOCID INT,
    CUS_NAME VARCHAR(200),
    CUS_LASTNAME VARCHAR(200),
    CUS_CTYID INT,
    CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY  (CUS_ID),
    CONSTRAINT FK_CUSDOC FOREIGN KEY  (CUS_DOCID) REFERENCES DOCUMENT(DOC_ID),
    CONSTRAINT FK_CUSCITY FOREIGN KEY (CUS_CTYID) REFERENCES CITY(CTY_ID)
);

CREATE TABLE CUSTOMER_ADD(
    ADD_ID INT AUTO_INCREMENT,
    ADD_CUSID INT,
    ADD_ADDRESS VARCHAR(200),
    CONSTRAINT PK_CUSTOMER_ADD_ID PRIMARY KEY  (ADD_ID),
    CONSTRAINT FK_ADDCUS FOREIGN KEY  (ADD_CUSID) REFERENCES CUSTOMER(CUS_ID)
);

CREATE TABLE CUSTOMER_CEL(
    CEL_ID INT AUTO_INCREMENT,
    CEL_CUSID INT,
    CEL_CELLPHONE VARCHAR(15),
    CONSTRAINT PK_CUSTOMER_CEL_ID PRIMARY KEY  (CEL_ID),
    CONSTRAINT FK_CELCUS FOREIGN KEY  (CEL_CUSID) REFERENCES CUSTOMER(CUS_ID)
);

CREATE TABLE PRODUCT(
    PRD_ID INT AUTO_INCREMENT,
    PRD_DESCRIPTION VARCHAR(100),
    PRD_PRICE DECIMAL,
    PRD_COST DECIMAL,
    PRD_STOCK DECIMAL,
    PRD_PDTID INT,
    PRD_SUPID INT,
    PRD_ENTRY_DATE DATE,
    CONSTRAINT PK_PRODUCT_ID PRIMARY KEY  (PRD_ID),
    CONSTRAINT FK_PRODUCTTYPE FOREIGN KEY  (PRD_PDTID) REFERENCES PRODUCT_TYPE(PDT_ID),
    CONSTRAINT FK_PRD_SUPPLIER FOREIGN KEY  (PRD_SUPID) REFERENCES SUPPLIER(SUP_ID)
);

CREATE TABLE INVOICE(
    INV_ID INT AUTO_INCREMENT,
    INV_MTPID INT,
    INV_CUSID INT,
    INV_EMPLOYEE VARCHAR(50),
    INV_DATE DATE,
    INV_TOTAL DECIMAL(10,0),
    CONSTRAINT PK_INVOICE_ID PRIMARY KEY  (INV_ID),
    CONSTRAINT FK_INVMETHOD FOREIGN KEY  (INV_MTPID) REFERENCES METHOD_PAYMENT(MTP_ID),
    CONSTRAINT FK_INVCUSTOMER FOREIGN KEY  (INV_CUSID) REFERENCES CUSTOMER(CUS_ID)
);

CREATE TABLE INVOICE_DETAIL(
    DET_INVID INT,
    DET_PRDID INT,
    DET_QUANTITY DECIMAL,
    DET_TOTAL DECIMAL(10,0),
    CONSTRAINT FK_DETINVOICE FOREIGN KEY  (DET_INVID) REFERENCES INVOICE(INV_ID),
    CONSTRAINT FK_DETPRODUCT FOREIGN KEY  (DET_PRDID) REFERENCES PRODUCT(PRD_ID)
);

--CREATE TABLE REPAYMENT();