CREATE DATABASE WIKISALES;

CREATE TABLE DOCUMENT_TYPE(
    DCT_ID INT AUTO_INCREMENT,
    DCT_DESCRIPTION VARCHAR(20),
    CONSTRAINT PK_DOCUMENT_ID PRIMARY KEY  DCT_ID
);

CREATE TABLE CITY(
    CTY_ID INT AUTO_INCREMENT,
    CTY_NAME VARCHAR(200),
    CONSTRAINT PK_CITY_ID PRIMARY KEY  CTY_ID
);

CREATE TABLE PRODUCT_TYPE(
    PDT_ID INT AUTO_INCREMENT,
    PDT_DESCRIPTION VARCHAR(20),
    CONSTRAINT PK_PRODUCT_TYPE_ID PRIMARY KEY  PDT
);

CREATE TABLE METHOD_PAYMENT(
    MTP_ID INT AUTO_INCREMENT,
    MTP_DESCRIPTION VARCHAR(20),
    CONSTRAINT PK_METHOD_PAYMENT_ID PRIMARY KEY  MTP_ID
);

CREATE TABLE DOCUMENT(
    DOC_ID INT AUTO_INCREMENT,
    DOC_NUMBER VARCHAR(20),
    DOC_DCTID INT,
    CONSTRAINT PK_CUSTOMER_DOC_ID PRIMARY KEY  DOC_ID,
    CONSTRAINT FK_DOCUMENT_TYPE FOREIGN KEY  DOC_DCTID REFERENCES DOCUMENT_TYPE(DCT_ID)
);

CREATE TABLE SUPPLIER(
    SUP_ID INT AUTO_INCREMENT,
    SUP_NAME VARCHAR(20),
    SUP_LASTNAME VARCHAR(20),
    SUP_TRADENAME VARCHAR(50),
    SUP_ADDRESS VARCHAR(200),
    SUP_CTYID INT,
    SUP_DOCID INT,
    CONSTRAINT PK_SUPPLIER_ID PRIMARY KEY  SUP_ID,
    CONSTRAINT FK_SUPCITY FOREIGN KEY  SUP_CTYID REFERENCES CITY(CTY_ID), 
    CONSTRAINT FK_SUPDOC FOREIGN KEY  SUP_DOCID REFERENCES DOCUMENT(DOC_ID)
);

CREATE TABLE CUSTOMER_TYPE(
    CUT_ID INT AUTO_INCREMENT,
    CUT_DESCRIPTION VARCHAR(20),
    CONSTRAINT PK_CUSTOMER_TYPE_ID PRIMARY KEY  CUT_ID
);

CREATE TABLE CUSTOMER(
    CUS_ID INT AUTO_INCREMENT,
    CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY  CUS_ID
);

CREATE TABLE CUSTOMER_ADD(
    DIR_ID INT AUTO_INCREMENT,
    CONSTRAINT PK_CUSTOMER_DIR_ID PRIMARY KEY  DIR_ID
);

CREATE TABLE CUSTOMER_CEL(
    CEL_ID INT AUTO_INCREMENT,
    CONSTRAINT PK_CUSTOMER_CEL_ID PRIMARY KEY  CEL_ID
);

CREATE TABLE PRODUCT(
    PRD_ID INT AUTO_INCREMENT,
    CONSTRAINT PK_PRODUCT_ID PRIMARY KEY  PRD_ID
);

CREATE TABLE INVOICE(
    INV_ID INT AUTO_INCREMENT,
    CONSTRAINT PK_INVOICE_ID PRIMARY KEY  INV_ID
);

CREATE TABLE INVOICE_DETAIL();

CREATE TABLE REPAYMENT();